name: Trigger Update From Template

on:
  pull_request:
    branches:
      - master
    types:
      - closed

permissions:
  pull-requests: write

jobs:
  trigger-update-from-template:
    uses: infrastructure-blocks/trigger-update-from-template-workflow/.github/workflows/workflow.yml@v2
    secrets:
      github-pat: ${{ secrets.PAT }}
