name: Your Reusable Workflow

on:
  workflow_call:
    inputs:
      node-version-file:
        type: string
        description: The NodeJs version file passed to actions/setup-node.
        required: false
      node-version:
        type: string
        description: The NodeJS version passed to actions/setup-node.
        required: false
    secrets:
      codecov-token:
        description: The Codecov token to publish code coverage.
        required: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Parse inputs
        id: parse-inputs
        run: |
          echo "with-coverage=${{ secrets.codecov-token != '' }}" >> "${GITHUB_OUTPUT}"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node-version-file }}
          node-version: ${{ inputs.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run compile
      - run: npm run build
      - run: npm run lint
      - run: npm run test:coverage:lcov
      - if: ${{ steps.parse-inputs.outputs.with-coverage == 'true' }}
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.codecov-token }}
